### ISSUE TITLE
Publish to CF plugin repository

### ISSUE THREAD

**Issue by dcarley** [alphagov/paas-cf-conduit#11]
Publish to https://plugins.cloudfoundry.org/ when we're happy user feedback and quality.

**Comment by LeePorte** [comment]
I'd also suggest posting to the CF Dev mailing list.

**Comment by chrisfarms** [comment]
We might want to consider how this might be used for non-rdsbroker services before announcing to wider cf community. 

While having a helper to setup tunnels is definitely useful for all services from all brokers, I believe the more useful function is the wrapping of mysql/psql tools.... which currently relies on our service naming and credentials format for detection. 

I have created #13 to explain the issue in more detail

**Comment by chrisfarms** [comment]
The plugin has been published
