### ISSUE TITLE
Signals not forwarded to foreground commands

### ISSUE THREAD

**Issue by chrisfarms** [alphagov/paas-cf-conduit#23]
## Steps to reproduce

Start a conduit to a shell/repl type command:

```
cf conduit mything -- psql
```

Send ctrl+c.

## Expected behaviour

`psql` handles the ctrl+c as it sees fit ... in this case "clear the current input"

## Observed behaviour

Get booted out of the psql session and the conduit closes.

## Potential fix

When running a foreground command, signals should be forwarded to the child command.

**Comment by bandesz** [comment]
This is now solved with the latest release (0.0.4)
