### ISSUE TITLE
"Access denied for user" -- how to diagnose

### ISSUE THREAD

**Issue by RichardBradley** [alphagov/paas-cf-conduit#29]
Hi,

I am developing an application on the GOV.UK PaaS for BEIS.

I have a GOV.UK PaaS account, and I have created a database with the following commands:

```
cf login -a api.cloud.service.gov.uk -u *** -p ***
cf target -o ***
cf create-space int
cf target -o *** -s "int"
cf create-service mysql Free myapp-database 
# wait until the database service is ready
cf install-plugin conduit
```

When I attempt to connect to the database with the following command:

```
cf conduit myapp-database -- mysql
```

I get the following error:

```
ERROR 1045 (28000): Access denied for user 'un73dmsmf7wo7anm'@'10.0.34.10' (using password: YES)
```

Does anyone know how I can diagnose or fix this issue?

Many thanks,

Rich

**Comment by alext** [comment]
Hi Richard,

Please can you raise a support ticket with us about this (details here: https://www.cloud.service.gov.uk/support).

In the meantime, I'm going to close this issue.

thanks,
Alex

**Comment by RichardBradley** [comment]
Thanks, will do
