### ISSUE TITLE
Proxy Authentication Required

### ISSUE THREAD

**Issue by MichaelStevenson2207** [alphagov/paas-cf-conduit#49]
Hello,

I am installing Conduit for the first time but keep getting a Proxy Authentication error. I am using a Windows pc in our corporate environment. I have proxy settings set in my environment variables that allow me to use PaaS and Cloud Foundry okay however I cannot install this plugin. Is there any other alternatives for this or any ideas to help me? Thanks...

```
Searching CF-Community for plugin conduit...
Get https://plugins.cloudfoundry.org/list: Proxy Authentication Required
FAILED
```

**Comment by AP-Hunt** [comment]
Hi Michael,

An alternative approach is to download a release from this repo, and install it with `cf install-plugin /path/to/release`.

Regards,
Andy

**Comment by MichaelStevenson2207** [comment]
@AP-Hunt  Oh ok grand I'll give that a go sure thanks!

**Comment by AP-Hunt** [comment]
Let me know how it goes, and we'll get this closed off or help further :+1:

**Comment by MichaelStevenson2207** [comment]
@AP-Hunt You can close this issue thanks
