### ISSUE TITLE
Cleanup after exit

### ISSUE THREAD

**Issue by dcarley** [alphagov/paas-cf-conduit#5]
## What

Delete the `__conduit_XXXXX__` application and service binding when the utility exits.

If necessary, change the instructions to use ^D (close STDIN) rather than ^C (send SIGTERM).

## Why

So that the application doesn't use resource quotas and the service credentials are revoked.

**Comment by dcarley** [comment]
Oh, I've just seen #2. I guess this only happens if you're not using the `-- <cmd>` syntax? Is that expected at the moment?

**Comment by chrisfarms** [comment]
Were you testing with the 0.0.1 version? It should be resolved in the 0.0.2 release (or master) we did yesterday.

It can take a couple of seconds to get deleted (async delete).

There is also an known edge case where you SIGTERM after the create request, but before the response that causes it to stay around (ie a very badly timed Ctrl+C during the "Creating conduit" step... but I'm guessing you are referring to a normal/healthly exit situation?

**Comment by dcarley** [comment]
I thought I was using 0.0.2 but now that I look more closely it seems that I downloaded the wrong version and that it does work correctly in 0.0.2

Closing, my bad!
