### ISSUE TITLE
Unable to delete database / conduit app

### ISSUE THREAD

**Issue by davidjamesstone** [alphagov/paas-cf-conduit#50]
Hi 

I've managed to get myself in a bit of a situation and I was hoping someone here might be able to help.

While testing paas, I have created a cf postgres service called `pg-svc`. I have then used the conduit plugin to connect to the instance and run `psql`. During the session I have then made some changes to the db as the (I believe) temporary pg role created by the conduit plugin.

Somehow though I have managed to disconnect the conduit session but the related conduit app (__conduit_bupby9jm__) has not been removed, it's still there in `cf apps` and on the gov.paas dashboard. The temp conduit user role is also still in the pg db.

I now can't remove the conduit app because `Service broker error: pq: role "ugzehw_usjxjqmqt" cannot be dropped because some objects depend on it`. Neither can I remove the pg service because `Cannot delete service instance. Service keys, bindings, and shares must first be deleted.`

If I try and unbind the service with `cf unbind-service __conduit_bupby9jm__ pg-svc` I get the same `n unbind operation for the service binding between app __conduit_bupby9jm__ and service instance xws-db failed: Service broker error: pq: role "ugzehw_usjxjqmqt" cannot be dropped because some objects depend on it`

I'm not sure what the pg objects are that depend on the temp conduit role as I don't fully recall what scripts I ran but querying the db doesn't seem to report any objects actually being owned by that role. I have tried to `REASSIGN OWNED BY __conduit_bupby9jm__ TO anotherrole;` but I don't have sufficient permissions and when I set the db up, I didn't specify CREATEROLE so I'm unable to give myself permission.

I hope that makes sense to someone. I can't even delete the space because of the above issues. Shy of trying to fully delete the org, I'm out of ideas. Any help would really be appreciated - thanks.

**Comment by AP-Hunt** [comment]
Hi David,

Sounds like you're in a bit of a pickle there, sorry :/ This sounds like something better serviced as a support ticket in Zendesk, which I'll raise for you. Is the email address on your GitHub profile OK to use? Or do you have a preferred address?

Regards,
Andy

**Comment by davidjamesstone** [comment]
Thanks for your help, Andy.

If you could that would be great. My email is davidjamesstone@gmail.com or david.stone1@environment-agency.gov.uk please.

**Comment by AP-Hunt** [comment]
I've created the ticket in Zendesk, and you should have an email about it. I'll close this issue off so as not to confuse things.

**Comment by davidjamesstone** [comment]
That's great - thanks for all your help, Andy 👍
